import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

import { poppins } from "@/app/ui/fonts";
import Navbar from "./ui/navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html data-theme="light" lang="en">
			<Script src="https://kit.fontawesome.com/c0fa11f9f4.js"></Script>
			<body
				className={`${poppins.className} bg-base-100 text-base-content w-full`}
			>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
