import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="drawer lg:drawer-open">
			<input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
			<div className="drawer-content flex flex-col items-center">
				{children}
				<label
					htmlFor="my-drawer-2"
					className="btn btn-primary drawer-button lg:hidden fixed bottom-0 left-0 m-4"
				>
					<i className="fa-solid fa-bars"></i>
				</label>
			</div>
			<div className="drawer-side">
				<label
					htmlFor="my-drawer-2"
					aria-label="close sidebar"
					className="drawer-overlay"
				></label>
				<ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4">
					{/* Sidebar content here */}
					<li>
						<Link href="/main/dashboard">Dashboard</Link>
					</li>
					<li>
						<Link href="/main/classes">Classes</Link>
					</li>
				</ul>
			</div>
		</div>
	);
}
